spring:
  application:
    name: edoc

  datasource:
    url: ${EDOC_DB_URL:jdbc:postgresql://localhost:5432/edoc?currentSchema=public&charSet=UTF8}
    username: ${EDOC_DB_USER:postgres}
    password: ${EDOC_DB_PASSWORD:saadmin}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0

server:
  port: 4102

edoc:
  enabled: true
  base-url: https://edocument.ge/TEST/
#  export-service-url: https://edocument.ge/TEST/integrationservice/eDocumentExportService.svc/bhb
  export-service-url: https://srv5.edocument.ge/GNCC/integrationservice/eDocumentExportService.svc/bhb
#  wsdl-url: https://edocument.ge/TEST/integrationservice/eDocumentExportService.svc?wsdl
  wsdl-url: https://srv5.edocument.ge/GNCC/integrationservice/eDocumentExportService.svc?wsdl
#  client-auth-token: "{BD081743-C0C4-43B6-A0C3-30914FC9888F}"
  service-version: "1.0.0.0"
  connect-timeout-millis: 10000
  read-timeout-millis: 60000
  max-text-length: ${EDOC_MAX_TEXT_LENGTH:536870912}


cxf:
  logging:
    enabled: true
    limit: -1
