spring:
  application:
    name: edoc

  datasource:
    url: ${ANUBIS_DB_URL:jdbc:postgresql://localhost:5432/anubis?currentSchema=public&charSet=UTF8}
    username: ${ANUBIS_DB_USER:postgres}
    password: ${ANUBIS_DB_PASSWORD:saadmin}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    table: edoc_flyway_schema_history
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0

server:
  port: 4102

edoc:
  enabled: true
  base-url: https://edocument.ge/TEST/
  export-service-url: https://edocument.ge/TEST/integrationservice/eDocumentExportService.svc/bhb
  wsdl-url: https://edocument.ge/TEST/integrationservice/eDocumentExportService.svc?wsdl
  client-auth-token: "{BD081743-C0C4-43B6-A0C3-30914FC9888F}"
  service-version: "1.0.0.0"
  connect-timeout-millis: 10000
  read-timeout-millis: 60000


cxf:
  logging:
    enabled: true
    limit: -1
