spring.datasource.url=${EDOC_DB_URL:jdbc:postgresql://localhost:5432/edoc?currentSchema=public&charSet=UTF8}
spring.datasource.username=${EDOC_DB_USER:postgres}
spring.datasource.password=${EDOC_DB_PASSWORD:saadmin}
