//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdocBridge.edoc
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventFault", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.SystemFaults.Faults")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EdocBridge.edoc.ValidationFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EdocBridge.edoc.OperationFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EdocBridge.edoc.InternalFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EdocBridge.edoc.SecurityFault))]
    public partial class EventFault : object
    {
        
        private string FaultMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaultMessage
        {
            get
            {
                return this.FaultMessageField;
            }
            set
            {
                this.FaultMessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.SystemFaults.Faults")]
    public partial class ValidationFault : EdocBridge.edoc.EventFault
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationFault", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.SystemFaults.Faults")]
    public partial class OperationFault : EdocBridge.edoc.EventFault
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InternalFault", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.SystemFaults.Faults")]
    public partial class InternalFault : EdocBridge.edoc.EventFault
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecurityFault", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.SystemFaults.Faults")]
    public partial class SecurityFault : EdocBridge.edoc.EventFault
    {
        
        private EdocBridge.edoc.SecurityFaultCodes FaultCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdocBridge.edoc.SecurityFaultCodes FaultCode
        {
            get
            {
                return this.FaultCodeField;
            }
            set
            {
                this.FaultCodeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecurityFaultCodes", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.SystemFaults.Faults")]
    public enum SecurityFaultCodes : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UniqueSessionRequirementViolation = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IdleSessionTimeoutRequirementViolation = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IdleSessionTimeoutRequirementViolationWarning = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ActiveSessionRequirementViolation = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidLoginOrPassword = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidAuthenticationFactorType = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AuthenticationFactorTimeout = 7,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentTypes", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.Integration.DataContrac" +
        "ts")]
    public enum DocumentTypes : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Incoming = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Outgoing = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Internal = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Order = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IntegrationDataContract", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.ExternalServices.Core")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EdocBridge.edoc.Contact))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EdocBridge.edoc.PhysicalPerson))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EdocBridge.edoc.Organization))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EdocBridge.edoc.StateStructure))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EdocBridge.edoc.Document))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EdocBridge.edoc.DocumentData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EdocBridge.edoc.DocumentFile))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EdocBridge.edoc.RelatedDocument))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EdocBridge.edoc.DocumentInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EdocBridge.edoc.Process))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EdocBridge.edoc.ResponsibleData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EdocBridge.edoc.EmployeeData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EdocBridge.edoc.TaskData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EdocBridge.edoc.PreparationProcess))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EdocBridge.edoc.SignatureData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EdocBridge.edoc.ViseData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EdocBridge.edoc.ResultProcess))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EdocBridge.edoc.IncomingDocumentData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EdocBridge.edoc.ReceiveWayData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EdocBridge.edoc.InternalDocumentData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EdocBridge.edoc.OutgoingDocumentData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EdocBridge.edoc.OrderDocumentData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EdocBridge.edoc.DatePeriod))]
    public partial class IntegrationDataContract : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contact", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.Integration.Export")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EdocBridge.edoc.PhysicalPerson))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EdocBridge.edoc.Organization))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EdocBridge.edoc.StateStructure))]
    public partial class Contact : EdocBridge.edoc.IntegrationDataContract
    {
        
        private EdocBridge.edoc.ContactTypes ContactTypeField;
        
        private System.Guid IDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdocBridge.edoc.ContactTypes ContactType
        {
            get
            {
                return this.ContactTypeField;
            }
            set
            {
                this.ContactTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhysicalPerson", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.Integration.Export")]
    public partial class PhysicalPerson : EdocBridge.edoc.Contact
    {
        
        private string FirstNameField;
        
        private string LastNameField;
        
        private string PersonalNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonalNumber
        {
            get
            {
                return this.PersonalNumberField;
            }
            set
            {
                this.PersonalNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Organization", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.Integration.Export")]
    public partial class Organization : EdocBridge.edoc.Contact
    {
        
        private string IdentificationNumberField;
        
        private string JuridicalFormField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentificationNumber
        {
            get
            {
                return this.IdentificationNumberField;
            }
            set
            {
                this.IdentificationNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JuridicalForm
        {
            get
            {
                return this.JuridicalFormField;
            }
            set
            {
                this.JuridicalFormField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StateStructure", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.Integration.Export")]
    public partial class StateStructure : EdocBridge.edoc.Contact
    {
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Document", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.Integration.Export")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EdocBridge.edoc.DocumentData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EdocBridge.edoc.IncomingDocumentData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EdocBridge.edoc.InternalDocumentData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EdocBridge.edoc.OutgoingDocumentData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EdocBridge.edoc.OrderDocumentData))]
    public partial class Document : EdocBridge.edoc.IntegrationDataContract
    {
        
        private string CategoryField;
        
        private System.Nullable<System.DateTime> DeadlineField;
        
        private EdocBridge.edoc.DocumentStatuses DocumentStatusField;
        
        private EdocBridge.edoc.DocumentTypes DocumentTypeField;
        
        private EdocBridge.edoc.ExportStatuses ExportStatusField;
        
        private System.Guid IDField;
        
        private string IssueDecisionTypeField;
        
        private string NumberField;
        
        private System.DateTime RegistrationDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category
        {
            get
            {
                return this.CategoryField;
            }
            set
            {
                this.CategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Deadline
        {
            get
            {
                return this.DeadlineField;
            }
            set
            {
                this.DeadlineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdocBridge.edoc.DocumentStatuses DocumentStatus
        {
            get
            {
                return this.DocumentStatusField;
            }
            set
            {
                this.DocumentStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdocBridge.edoc.DocumentTypes DocumentType
        {
            get
            {
                return this.DocumentTypeField;
            }
            set
            {
                this.DocumentTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdocBridge.edoc.ExportStatuses ExportStatus
        {
            get
            {
                return this.ExportStatusField;
            }
            set
            {
                this.ExportStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IssueDecisionType
        {
            get
            {
                return this.IssueDecisionTypeField;
            }
            set
            {
                this.IssueDecisionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number
        {
            get
            {
                return this.NumberField;
            }
            set
            {
                this.NumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RegistrationDate
        {
            get
            {
                return this.RegistrationDateField;
            }
            set
            {
                this.RegistrationDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentData", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.Integration.Export")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EdocBridge.edoc.IncomingDocumentData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EdocBridge.edoc.InternalDocumentData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EdocBridge.edoc.OutgoingDocumentData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EdocBridge.edoc.OrderDocumentData))]
    public partial class DocumentData : EdocBridge.edoc.Document
    {
        
        private string AnnotationField;
        
        private string ChancellaryField;
        
        private string CommentsField;
        
        private EdocBridge.edoc.DocumentFile[] FilesField;
        
        private EdocBridge.edoc.PurposeTypes PurposeField;
        
        private EdocBridge.edoc.RelatedDocument[] RelatedDocumentsField;
        
        private EdocBridge.edoc.ResultProcess ResultProcessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Annotation
        {
            get
            {
                return this.AnnotationField;
            }
            set
            {
                this.AnnotationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Chancellary
        {
            get
            {
                return this.ChancellaryField;
            }
            set
            {
                this.ChancellaryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comments
        {
            get
            {
                return this.CommentsField;
            }
            set
            {
                this.CommentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdocBridge.edoc.DocumentFile[] Files
        {
            get
            {
                return this.FilesField;
            }
            set
            {
                this.FilesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdocBridge.edoc.PurposeTypes Purpose
        {
            get
            {
                return this.PurposeField;
            }
            set
            {
                this.PurposeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdocBridge.edoc.RelatedDocument[] RelatedDocuments
        {
            get
            {
                return this.RelatedDocumentsField;
            }
            set
            {
                this.RelatedDocumentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdocBridge.edoc.ResultProcess ResultProcess
        {
            get
            {
                return this.ResultProcessField;
            }
            set
            {
                this.ResultProcessField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentFile", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.Integration.Export")]
    public partial class DocumentFile : EdocBridge.edoc.IntegrationDataContract
    {
        
        private byte[] ContentField;
        
        private EdocBridge.edoc.DocumentFileTypes FileTypeField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdocBridge.edoc.DocumentFileTypes FileType
        {
            get
            {
                return this.FileTypeField;
            }
            set
            {
                this.FileTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RelatedDocument", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.Integration.Export")]
    public partial class RelatedDocument : EdocBridge.edoc.IntegrationDataContract
    {
        
        private EdocBridge.edoc.DocumentInfo DocumentField;
        
        private EdocBridge.edoc.RelationTypes RelationTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdocBridge.edoc.DocumentInfo Document
        {
            get
            {
                return this.DocumentField;
            }
            set
            {
                this.DocumentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdocBridge.edoc.RelationTypes RelationType
        {
            get
            {
                return this.RelationTypeField;
            }
            set
            {
                this.RelationTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentInfo", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.Integration.Export")]
    public partial class DocumentInfo : EdocBridge.edoc.IntegrationDataContract
    {
        
        private EdocBridge.edoc.DocumentTypes DocumentTypeField;
        
        private System.Nullable<EdocBridge.edoc.ExportStatuses> ExportStatusField;
        
        private System.Nullable<System.Guid> IDField;
        
        private string NumberField;
        
        private System.DateTime RegistrationDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdocBridge.edoc.DocumentTypes DocumentType
        {
            get
            {
                return this.DocumentTypeField;
            }
            set
            {
                this.DocumentTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<EdocBridge.edoc.ExportStatuses> ExportStatus
        {
            get
            {
                return this.ExportStatusField;
            }
            set
            {
                this.ExportStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number
        {
            get
            {
                return this.NumberField;
            }
            set
            {
                this.NumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RegistrationDate
        {
            get
            {
                return this.RegistrationDateField;
            }
            set
            {
                this.RegistrationDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Process", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.Integration.Export")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EdocBridge.edoc.PreparationProcess))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EdocBridge.edoc.ResultProcess))]
    public partial class Process : EdocBridge.edoc.IntegrationDataContract
    {
        
        private EdocBridge.edoc.ResponsibleData[] ResponsiblesField;
        
        private EdocBridge.edoc.TaskData TaskField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdocBridge.edoc.ResponsibleData[] Responsibles
        {
            get
            {
                return this.ResponsiblesField;
            }
            set
            {
                this.ResponsiblesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdocBridge.edoc.TaskData Task
        {
            get
            {
                return this.TaskField;
            }
            set
            {
                this.TaskField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponsibleData", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.Integration.Export")]
    public partial class ResponsibleData : EdocBridge.edoc.IntegrationDataContract
    {
        
        private EdocBridge.edoc.ResponsibleData[] ChildResponsiblesField;
        
        private System.DateTime DeadlineField;
        
        private EdocBridge.edoc.EmployeeData EmployeeField;
        
        private System.DateTime StartDateField;
        
        private EdocBridge.edoc.ResponsibleStatuses StatusField;
        
        private System.DateTime StatusChangeDateField;
        
        private string TaskField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdocBridge.edoc.ResponsibleData[] ChildResponsibles
        {
            get
            {
                return this.ChildResponsiblesField;
            }
            set
            {
                this.ChildResponsiblesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Deadline
        {
            get
            {
                return this.DeadlineField;
            }
            set
            {
                this.DeadlineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdocBridge.edoc.EmployeeData Employee
        {
            get
            {
                return this.EmployeeField;
            }
            set
            {
                this.EmployeeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdocBridge.edoc.ResponsibleStatuses Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StatusChangeDate
        {
            get
            {
                return this.StatusChangeDateField;
            }
            set
            {
                this.StatusChangeDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Task
        {
            get
            {
                return this.TaskField;
            }
            set
            {
                this.TaskField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeData", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.Integration.Export")]
    public partial class EmployeeData : EdocBridge.edoc.IntegrationDataContract
    {
        
        private string FirstNameField;
        
        private string LastNameField;
        
        private string OrganizationStructureField;
        
        private string PositionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrganizationStructure
        {
            get
            {
                return this.OrganizationStructureField;
            }
            set
            {
                this.OrganizationStructureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Position
        {
            get
            {
                return this.PositionField;
            }
            set
            {
                this.PositionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskData", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.Integration.Export")]
    public partial class TaskData : EdocBridge.edoc.IntegrationDataContract
    {
        
        private System.DateTime DeadlineField;
        
        private EdocBridge.edoc.EmployeeData InitiatedByField;
        
        private bool IsInitiatedField;
        
        private int NumberField;
        
        private System.DateTime StartDateField;
        
        private string TextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Deadline
        {
            get
            {
                return this.DeadlineField;
            }
            set
            {
                this.DeadlineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdocBridge.edoc.EmployeeData InitiatedBy
        {
            get
            {
                return this.InitiatedByField;
            }
            set
            {
                this.InitiatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsInitiated
        {
            get
            {
                return this.IsInitiatedField;
            }
            set
            {
                this.IsInitiatedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Number
        {
            get
            {
                return this.NumberField;
            }
            set
            {
                this.NumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text
        {
            get
            {
                return this.TextField;
            }
            set
            {
                this.TextField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PreparationProcess", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.Integration.Export")]
    public partial class PreparationProcess : EdocBridge.edoc.Process
    {
        
        private EdocBridge.edoc.SignatureData[] SignaturesField;
        
        private EdocBridge.edoc.ViseData[] VisesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdocBridge.edoc.SignatureData[] Signatures
        {
            get
            {
                return this.SignaturesField;
            }
            set
            {
                this.SignaturesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdocBridge.edoc.ViseData[] Vises
        {
            get
            {
                return this.VisesField;
            }
            set
            {
                this.VisesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignatureData", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.Integration.Export")]
    public partial class SignatureData : EdocBridge.edoc.IntegrationDataContract
    {
        
        private EdocBridge.edoc.EmployeeData CreatorField;
        
        private System.DateTime DeadlineField;
        
        private System.DateTime EntryDateField;
        
        private EdocBridge.edoc.EmployeeData SignatoryField;
        
        private EdocBridge.edoc.SignatureStatuses StatusField;
        
        private System.DateTime StatusChangeDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdocBridge.edoc.EmployeeData Creator
        {
            get
            {
                return this.CreatorField;
            }
            set
            {
                this.CreatorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Deadline
        {
            get
            {
                return this.DeadlineField;
            }
            set
            {
                this.DeadlineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EntryDate
        {
            get
            {
                return this.EntryDateField;
            }
            set
            {
                this.EntryDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdocBridge.edoc.EmployeeData Signatory
        {
            get
            {
                return this.SignatoryField;
            }
            set
            {
                this.SignatoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdocBridge.edoc.SignatureStatuses Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StatusChangeDate
        {
            get
            {
                return this.StatusChangeDateField;
            }
            set
            {
                this.StatusChangeDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ViseData", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.Integration.Export")]
    public partial class ViseData : EdocBridge.edoc.IntegrationDataContract
    {
        
        private EdocBridge.edoc.EmployeeData AuthorField;
        
        private EdocBridge.edoc.ViseData[] ChildVisesField;
        
        private EdocBridge.edoc.EmployeeData CreatorField;
        
        private System.DateTime DeadlineField;
        
        private System.DateTime EntryDateField;
        
        private EdocBridge.edoc.ViseStatuses StatusField;
        
        private System.DateTime StatusChangeDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdocBridge.edoc.EmployeeData Author
        {
            get
            {
                return this.AuthorField;
            }
            set
            {
                this.AuthorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdocBridge.edoc.ViseData[] ChildVises
        {
            get
            {
                return this.ChildVisesField;
            }
            set
            {
                this.ChildVisesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdocBridge.edoc.EmployeeData Creator
        {
            get
            {
                return this.CreatorField;
            }
            set
            {
                this.CreatorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Deadline
        {
            get
            {
                return this.DeadlineField;
            }
            set
            {
                this.DeadlineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EntryDate
        {
            get
            {
                return this.EntryDateField;
            }
            set
            {
                this.EntryDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdocBridge.edoc.ViseStatuses Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StatusChangeDate
        {
            get
            {
                return this.StatusChangeDateField;
            }
            set
            {
                this.StatusChangeDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultProcess", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.Integration.Export")]
    public partial class ResultProcess : EdocBridge.edoc.Process
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IncomingDocumentData", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.Integration.Export")]
    public partial class IncomingDocumentData : EdocBridge.edoc.DocumentData
    {
        
        private EdocBridge.edoc.EmployeeData[] AddresseesField;
        
        private System.Nullable<System.DateTime> OriginalDateField;
        
        private string OriginalNumberField;
        
        private EdocBridge.edoc.ReceiveWayData[] ReceiveWaysField;
        
        private EdocBridge.edoc.Contact[] SendersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdocBridge.edoc.EmployeeData[] Addressees
        {
            get
            {
                return this.AddresseesField;
            }
            set
            {
                this.AddresseesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> OriginalDate
        {
            get
            {
                return this.OriginalDateField;
            }
            set
            {
                this.OriginalDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginalNumber
        {
            get
            {
                return this.OriginalNumberField;
            }
            set
            {
                this.OriginalNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdocBridge.edoc.ReceiveWayData[] ReceiveWays
        {
            get
            {
                return this.ReceiveWaysField;
            }
            set
            {
                this.ReceiveWaysField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdocBridge.edoc.Contact[] Senders
        {
            get
            {
                return this.SendersField;
            }
            set
            {
                this.SendersField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiveWayData", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.Integration.Export")]
    public partial class ReceiveWayData : EdocBridge.edoc.IntegrationDataContract
    {
        
        private string CommentsField;
        
        private string WayField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comments
        {
            get
            {
                return this.CommentsField;
            }
            set
            {
                this.CommentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Way
        {
            get
            {
                return this.WayField;
            }
            set
            {
                this.WayField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InternalDocumentData", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.Integration.Export")]
    public partial class InternalDocumentData : EdocBridge.edoc.DocumentData
    {
        
        private bool HasDigitalSignatureField;
        
        private bool HasDigitalStampField;
        
        private EdocBridge.edoc.PreparationProcess PreProcessField;
        
        private EdocBridge.edoc.EmployeeData[] RecipientsField;
        
        private EdocBridge.edoc.EmployeeData[] SendersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasDigitalSignature
        {
            get
            {
                return this.HasDigitalSignatureField;
            }
            set
            {
                this.HasDigitalSignatureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasDigitalStamp
        {
            get
            {
                return this.HasDigitalStampField;
            }
            set
            {
                this.HasDigitalStampField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdocBridge.edoc.PreparationProcess PreProcess
        {
            get
            {
                return this.PreProcessField;
            }
            set
            {
                this.PreProcessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdocBridge.edoc.EmployeeData[] Recipients
        {
            get
            {
                return this.RecipientsField;
            }
            set
            {
                this.RecipientsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdocBridge.edoc.EmployeeData[] Senders
        {
            get
            {
                return this.SendersField;
            }
            set
            {
                this.SendersField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OutgoingDocumentData", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.Integration.Export")]
    public partial class OutgoingDocumentData : EdocBridge.edoc.DocumentData
    {
        
        private bool HasDigitalSignatureField;
        
        private bool HasDigitalStampField;
        
        private EdocBridge.edoc.PreparationProcess PreProcessField;
        
        private EdocBridge.edoc.Contact[] RecipientsField;
        
        private EdocBridge.edoc.EmployeeData[] SignatoriesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasDigitalSignature
        {
            get
            {
                return this.HasDigitalSignatureField;
            }
            set
            {
                this.HasDigitalSignatureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasDigitalStamp
        {
            get
            {
                return this.HasDigitalStampField;
            }
            set
            {
                this.HasDigitalStampField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdocBridge.edoc.PreparationProcess PreProcess
        {
            get
            {
                return this.PreProcessField;
            }
            set
            {
                this.PreProcessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdocBridge.edoc.Contact[] Recipients
        {
            get
            {
                return this.RecipientsField;
            }
            set
            {
                this.RecipientsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdocBridge.edoc.EmployeeData[] Signatories
        {
            get
            {
                return this.SignatoriesField;
            }
            set
            {
                this.SignatoriesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderDocumentData", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.Integration.Export")]
    public partial class OrderDocumentData : EdocBridge.edoc.DocumentData
    {
        
        private EdocBridge.edoc.OrderDirections DirectionField;
        
        private bool HasDigitalSignatureField;
        
        private bool HasDigitalStampField;
        
        private EdocBridge.edoc.EmployeeData[] InnerRecipientsField;
        
        private string OrderTypeField;
        
        private EdocBridge.edoc.Contact[] OuterRecipientsField;
        
        private EdocBridge.edoc.PreparationProcess PreProcessField;
        
        private EdocBridge.edoc.EmployeeData[] RelatedEmployeesField;
        
        private EdocBridge.edoc.EmployeeData[] SignatoriesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdocBridge.edoc.OrderDirections Direction
        {
            get
            {
                return this.DirectionField;
            }
            set
            {
                this.DirectionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasDigitalSignature
        {
            get
            {
                return this.HasDigitalSignatureField;
            }
            set
            {
                this.HasDigitalSignatureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasDigitalStamp
        {
            get
            {
                return this.HasDigitalStampField;
            }
            set
            {
                this.HasDigitalStampField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdocBridge.edoc.EmployeeData[] InnerRecipients
        {
            get
            {
                return this.InnerRecipientsField;
            }
            set
            {
                this.InnerRecipientsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderType
        {
            get
            {
                return this.OrderTypeField;
            }
            set
            {
                this.OrderTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdocBridge.edoc.Contact[] OuterRecipients
        {
            get
            {
                return this.OuterRecipientsField;
            }
            set
            {
                this.OuterRecipientsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdocBridge.edoc.PreparationProcess PreProcess
        {
            get
            {
                return this.PreProcessField;
            }
            set
            {
                this.PreProcessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdocBridge.edoc.EmployeeData[] RelatedEmployees
        {
            get
            {
                return this.RelatedEmployeesField;
            }
            set
            {
                this.RelatedEmployeesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdocBridge.edoc.EmployeeData[] Signatories
        {
            get
            {
                return this.SignatoriesField;
            }
            set
            {
                this.SignatoriesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatePeriod", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.Integration")]
    public partial class DatePeriod : EdocBridge.edoc.IntegrationDataContract
    {
        
        private System.DateTime FromField;
        
        private System.DateTime ToField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime From
        {
            get
            {
                return this.FromField;
            }
            set
            {
                this.FromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime To
        {
            get
            {
                return this.ToField;
            }
            set
            {
                this.ToField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactTypes", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.Integration.DataContrac" +
        "ts")]
    public enum ContactTypes : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PhysicalPerson = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Organization = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        StateStructure = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentStatuses", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.Integration.DataContrac" +
        "ts")]
    public enum DocumentStatuses : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Draft = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InProcess = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Completed = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExportStatuses", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.Integration.Export")]
    public enum ExportStatuses : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Exportable = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExportInProcess = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Exported = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExportFailed = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExportCanceled = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PurposeTypes", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.Integration.Export")]
    public enum PurposeTypes : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ForInformation = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ForReaction = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentFileTypes", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.Integration.DataContrac" +
        "ts")]
    public enum DocumentFileTypes : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Main = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Attachment = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RelationTypes", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.Integration.DataContrac" +
        "ts")]
    public enum RelationTypes : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Response = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Request = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Working = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponsibleStatuses", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.Integration.DataContrac" +
        "ts")]
    public enum ResponsibleStatuses : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Created = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Reviewed = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReRegistered = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SetCompleted = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CompletionConfirmed = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CompletionRejected = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignatureStatuses", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.Integration.DataContrac" +
        "ts")]
    public enum SignatureStatuses : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Created = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Reviewed = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rejected = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Signed = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Canceled = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ViseStatuses", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.Integration.DataContrac" +
        "ts")]
    public enum ViseStatuses : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Created = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Reviewed = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rejected = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Vised = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Canceled = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderDirections", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.Integration.DataContrac" +
        "ts")]
    public enum OrderDirections : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Internal = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Outgoing = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EdocBridge.edoc.IeDocumentExportService")]
    public interface IeDocumentExportService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IeDocumentExportService/LogOn", ReplyAction="http://tempuri.org/IeDocumentExportService/LogOnResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdocBridge.edoc.SecurityFault), Action="http://tempuri.org/IeDocumentExportService/LogOnSecurityFaultFault", Name="SecurityFault", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.SystemFaults.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdocBridge.edoc.ValidationFault), Action="http://tempuri.org/IeDocumentExportService/LogOnValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.SystemFaults.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdocBridge.edoc.OperationFault), Action="http://tempuri.org/IeDocumentExportService/LogOnOperationFaultFault", Name="OperationFault", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.SystemFaults.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdocBridge.edoc.InternalFault), Action="http://tempuri.org/IeDocumentExportService/LogOnInternalFaultFault", Name="InternalFault", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.SystemFaults.Faults")]
        System.Threading.Tasks.Task<System.Guid> LogOnAsync(string clientAuthenticationTocken, string serviceVersion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IeDocumentExportService/LogOut", ReplyAction="http://tempuri.org/IeDocumentExportService/LogOutResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdocBridge.edoc.SecurityFault), Action="http://tempuri.org/IeDocumentExportService/LogOutSecurityFaultFault", Name="SecurityFault", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.SystemFaults.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdocBridge.edoc.ValidationFault), Action="http://tempuri.org/IeDocumentExportService/LogOutValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.SystemFaults.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdocBridge.edoc.OperationFault), Action="http://tempuri.org/IeDocumentExportService/LogOutOperationFaultFault", Name="OperationFault", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.SystemFaults.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdocBridge.edoc.InternalFault), Action="http://tempuri.org/IeDocumentExportService/LogOutInternalFaultFault", Name="InternalFault", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.SystemFaults.Faults")]
        System.Threading.Tasks.Task LogOutAsync(System.Guid sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IeDocumentExportService/GetDocuments", ReplyAction="http://tempuri.org/IeDocumentExportService/GetDocumentsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdocBridge.edoc.SecurityFault), Action="http://tempuri.org/IeDocumentExportService/GetDocumentsSecurityFaultFault", Name="SecurityFault", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.SystemFaults.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdocBridge.edoc.ValidationFault), Action="http://tempuri.org/IeDocumentExportService/GetDocumentsValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.SystemFaults.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdocBridge.edoc.OperationFault), Action="http://tempuri.org/IeDocumentExportService/GetDocumentsOperationFaultFault", Name="OperationFault", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.SystemFaults.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdocBridge.edoc.InternalFault), Action="http://tempuri.org/IeDocumentExportService/GetDocumentsInternalFaultFault", Name="InternalFault", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.SystemFaults.Faults")]
        System.Threading.Tasks.Task<EdocBridge.edoc.Document[]> GetDocumentsAsync(System.Guid sessionID, EdocBridge.edoc.DocumentTypes documentType, EdocBridge.edoc.DatePeriod period, EdocBridge.edoc.Contact contact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IeDocumentExportService/GetDocument", ReplyAction="http://tempuri.org/IeDocumentExportService/GetDocumentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdocBridge.edoc.SecurityFault), Action="http://tempuri.org/IeDocumentExportService/GetDocumentSecurityFaultFault", Name="SecurityFault", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.SystemFaults.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdocBridge.edoc.ValidationFault), Action="http://tempuri.org/IeDocumentExportService/GetDocumentValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.SystemFaults.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdocBridge.edoc.OperationFault), Action="http://tempuri.org/IeDocumentExportService/GetDocumentOperationFaultFault", Name="OperationFault", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.SystemFaults.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdocBridge.edoc.InternalFault), Action="http://tempuri.org/IeDocumentExportService/GetDocumentInternalFaultFault", Name="InternalFault", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.SystemFaults.Faults")]
        System.Threading.Tasks.Task<EdocBridge.edoc.DocumentData> GetDocumentAsync(System.Guid sessionID, System.Guid documentID, bool getFullData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IeDocumentExportService/SetDocumentExported", ReplyAction="http://tempuri.org/IeDocumentExportService/SetDocumentExportedResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdocBridge.edoc.SecurityFault), Action="http://tempuri.org/IeDocumentExportService/SetDocumentExportedSecurityFaultFault", Name="SecurityFault", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.SystemFaults.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdocBridge.edoc.ValidationFault), Action="http://tempuri.org/IeDocumentExportService/SetDocumentExportedValidationFaultFaul" +
            "t", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.SystemFaults.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdocBridge.edoc.OperationFault), Action="http://tempuri.org/IeDocumentExportService/SetDocumentExportedOperationFaultFault" +
            "", Name="OperationFault", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.SystemFaults.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdocBridge.edoc.InternalFault), Action="http://tempuri.org/IeDocumentExportService/SetDocumentExportedInternalFaultFault", Name="InternalFault", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.SystemFaults.Faults")]
        System.Threading.Tasks.Task SetDocumentExportedAsync(System.Guid sessionID, System.Guid documentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IeDocumentExportService/GetPhysicalPersonsByPersonalNumber", ReplyAction="http://tempuri.org/IeDocumentExportService/GetPhysicalPersonsByPersonalNumberResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdocBridge.edoc.SecurityFault), Action="http://tempuri.org/IeDocumentExportService/GetPhysicalPersonsByPersonalNumberSecu" +
            "rityFaultFault", Name="SecurityFault", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.SystemFaults.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdocBridge.edoc.ValidationFault), Action="http://tempuri.org/IeDocumentExportService/GetPhysicalPersonsByPersonalNumberVali" +
            "dationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.SystemFaults.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdocBridge.edoc.OperationFault), Action="http://tempuri.org/IeDocumentExportService/GetPhysicalPersonsByPersonalNumberOper" +
            "ationFaultFault", Name="OperationFault", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.SystemFaults.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdocBridge.edoc.InternalFault), Action="http://tempuri.org/IeDocumentExportService/GetPhysicalPersonsByPersonalNumberInte" +
            "rnalFaultFault", Name="InternalFault", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.SystemFaults.Faults")]
        System.Threading.Tasks.Task<EdocBridge.edoc.PhysicalPerson[]> GetPhysicalPersonsByPersonalNumberAsync(System.Guid sessionID, string personalNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IeDocumentExportService/GetPhysicalPersonsByName", ReplyAction="http://tempuri.org/IeDocumentExportService/GetPhysicalPersonsByNameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdocBridge.edoc.SecurityFault), Action="http://tempuri.org/IeDocumentExportService/GetPhysicalPersonsByNameSecurityFaultF" +
            "ault", Name="SecurityFault", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.SystemFaults.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdocBridge.edoc.ValidationFault), Action="http://tempuri.org/IeDocumentExportService/GetPhysicalPersonsByNameValidationFaul" +
            "tFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.SystemFaults.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdocBridge.edoc.OperationFault), Action="http://tempuri.org/IeDocumentExportService/GetPhysicalPersonsByNameOperationFault" +
            "Fault", Name="OperationFault", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.SystemFaults.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdocBridge.edoc.InternalFault), Action="http://tempuri.org/IeDocumentExportService/GetPhysicalPersonsByNameInternalFaultF" +
            "ault", Name="InternalFault", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.SystemFaults.Faults")]
        System.Threading.Tasks.Task<EdocBridge.edoc.PhysicalPerson[]> GetPhysicalPersonsByNameAsync(System.Guid sessionID, string lastName, string firstName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IeDocumentExportService/GetOrganizationsByIdentificationNumber" +
            "", ReplyAction="http://tempuri.org/IeDocumentExportService/GetOrganizationsByIdentificationNumber" +
            "Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdocBridge.edoc.SecurityFault), Action="http://tempuri.org/IeDocumentExportService/GetOrganizationsByIdentificationNumber" +
            "SecurityFaultFault", Name="SecurityFault", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.SystemFaults.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdocBridge.edoc.ValidationFault), Action="http://tempuri.org/IeDocumentExportService/GetOrganizationsByIdentificationNumber" +
            "ValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.SystemFaults.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdocBridge.edoc.OperationFault), Action="http://tempuri.org/IeDocumentExportService/GetOrganizationsByIdentificationNumber" +
            "OperationFaultFault", Name="OperationFault", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.SystemFaults.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdocBridge.edoc.InternalFault), Action="http://tempuri.org/IeDocumentExportService/GetOrganizationsByIdentificationNumber" +
            "InternalFaultFault", Name="InternalFault", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.SystemFaults.Faults")]
        System.Threading.Tasks.Task<EdocBridge.edoc.Organization[]> GetOrganizationsByIdentificationNumberAsync(System.Guid sessionID, string identificationNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IeDocumentExportService/GetOrganizationsByName", ReplyAction="http://tempuri.org/IeDocumentExportService/GetOrganizationsByNameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdocBridge.edoc.SecurityFault), Action="http://tempuri.org/IeDocumentExportService/GetOrganizationsByNameSecurityFaultFau" +
            "lt", Name="SecurityFault", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.SystemFaults.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdocBridge.edoc.ValidationFault), Action="http://tempuri.org/IeDocumentExportService/GetOrganizationsByNameValidationFaultF" +
            "ault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.SystemFaults.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdocBridge.edoc.OperationFault), Action="http://tempuri.org/IeDocumentExportService/GetOrganizationsByNameOperationFaultFa" +
            "ult", Name="OperationFault", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.SystemFaults.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdocBridge.edoc.InternalFault), Action="http://tempuri.org/IeDocumentExportService/GetOrganizationsByNameInternalFaultFau" +
            "lt", Name="InternalFault", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.SystemFaults.Faults")]
        System.Threading.Tasks.Task<EdocBridge.edoc.Organization[]> GetOrganizationsByNameAsync(System.Guid sessionID, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IeDocumentExportService/GetStateStructures", ReplyAction="http://tempuri.org/IeDocumentExportService/GetStateStructuresResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdocBridge.edoc.SecurityFault), Action="http://tempuri.org/IeDocumentExportService/GetStateStructuresSecurityFaultFault", Name="SecurityFault", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.SystemFaults.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdocBridge.edoc.ValidationFault), Action="http://tempuri.org/IeDocumentExportService/GetStateStructuresValidationFaultFault" +
            "", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.SystemFaults.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdocBridge.edoc.OperationFault), Action="http://tempuri.org/IeDocumentExportService/GetStateStructuresOperationFaultFault", Name="OperationFault", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.SystemFaults.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdocBridge.edoc.InternalFault), Action="http://tempuri.org/IeDocumentExportService/GetStateStructuresInternalFaultFault", Name="InternalFault", Namespace="http://schemas.datacontract.org/2004/07/FAS.DocManagement.SystemFaults.Faults")]
        System.Threading.Tasks.Task<EdocBridge.edoc.StateStructure[]> GetStateStructuresAsync(System.Guid sessionID, string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IeDocumentExportServiceChannel : EdocBridge.edoc.IeDocumentExportService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class IeDocumentExportServiceClient : System.ServiceModel.ClientBase<EdocBridge.edoc.IeDocumentExportService>, EdocBridge.edoc.IeDocumentExportService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public IeDocumentExportServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(IeDocumentExportServiceClient.GetBindingForEndpoint(endpointConfiguration), IeDocumentExportServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IeDocumentExportServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(IeDocumentExportServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IeDocumentExportServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(IeDocumentExportServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IeDocumentExportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<System.Guid> LogOnAsync(string clientAuthenticationTocken, string serviceVersion)
        {
            return base.Channel.LogOnAsync(clientAuthenticationTocken, serviceVersion);
        }
        
        public System.Threading.Tasks.Task LogOutAsync(System.Guid sessionID)
        {
            return base.Channel.LogOutAsync(sessionID);
        }
        
        public System.Threading.Tasks.Task<EdocBridge.edoc.Document[]> GetDocumentsAsync(System.Guid sessionID, EdocBridge.edoc.DocumentTypes documentType, EdocBridge.edoc.DatePeriod period, EdocBridge.edoc.Contact contact)
        {
            return base.Channel.GetDocumentsAsync(sessionID, documentType, period, contact);
        }
        
        public System.Threading.Tasks.Task<EdocBridge.edoc.DocumentData> GetDocumentAsync(System.Guid sessionID, System.Guid documentID, bool getFullData)
        {
            return base.Channel.GetDocumentAsync(sessionID, documentID, getFullData);
        }
        
        public System.Threading.Tasks.Task SetDocumentExportedAsync(System.Guid sessionID, System.Guid documentID)
        {
            return base.Channel.SetDocumentExportedAsync(sessionID, documentID);
        }
        
        public System.Threading.Tasks.Task<EdocBridge.edoc.PhysicalPerson[]> GetPhysicalPersonsByPersonalNumberAsync(System.Guid sessionID, string personalNumber)
        {
            return base.Channel.GetPhysicalPersonsByPersonalNumberAsync(sessionID, personalNumber);
        }
        
        public System.Threading.Tasks.Task<EdocBridge.edoc.PhysicalPerson[]> GetPhysicalPersonsByNameAsync(System.Guid sessionID, string lastName, string firstName)
        {
            return base.Channel.GetPhysicalPersonsByNameAsync(sessionID, lastName, firstName);
        }
        
        public System.Threading.Tasks.Task<EdocBridge.edoc.Organization[]> GetOrganizationsByIdentificationNumberAsync(System.Guid sessionID, string identificationNumber)
        {
            return base.Channel.GetOrganizationsByIdentificationNumberAsync(sessionID, identificationNumber);
        }
        
        public System.Threading.Tasks.Task<EdocBridge.edoc.Organization[]> GetOrganizationsByNameAsync(System.Guid sessionID, string name)
        {
            return base.Channel.GetOrganizationsByNameAsync(sessionID, name);
        }
        
        public System.Threading.Tasks.Task<EdocBridge.edoc.StateStructure[]> GetStateStructuresAsync(System.Guid sessionID, string name)
        {
            return base.Channel.GetStateStructuresAsync(sessionID, name);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CustomBinding_IeDocumentExportService))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                result.Elements.Add(new System.ServiceModel.Channels.BinaryMessageEncodingBindingElement());
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IeDocumentExportService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CustomBinding_IeDocumentExportService))
            {
                return new System.ServiceModel.EndpointAddress("https://edocument.ge/TEST/integrationservice/eDocumentExportService.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IeDocumentExportService))
            {
                return new System.ServiceModel.EndpointAddress("https://edocument.ge/TEST/integrationservice/eDocumentExportService.svc/bhb");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            CustomBinding_IeDocumentExportService,
            
            BasicHttpBinding_IeDocumentExportService,
        }
    }
}
